# Form implementation generated from reading ui file 'f:\Estudios\Visual Studio Code\2ºDAM\Interfaces\trabajo\Designs\Imprimir.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(479, 497)
        Frame.setStyleSheet("QFrame {\n"
"background-color: rgb(18, 18, 18);\n"
"border: 3px solid rgb(239, 205, 129);\n"
"}\n"
"\n"
"QDateEdit {\n"
"background-color: rgb(18, 18, 18);\n"
"color: rgb(239, 205, 129);\n"
"font: 20px;\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: rgb(237, 201, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(247, 222, 153);\n"
"}\n"
"\n"
"QToolButton {\n"
"background-color: rgb(237, 201, 125);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgb(247, 222, 153);\n"
"}\n"
"")
        self.FechaInicial = QtWidgets.QDateEdit(parent=Frame)
        self.FechaInicial.setGeometry(QtCore.QRect(40, 90, 151, 51))
        self.FechaInicial.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"color: rgb(239, 205, 129);\n"
"selection-background-color: rgb(207, 175, 110);\n"
"selection-color: rgb(20, 20, 20);\n"
"alternate-background-color: rgb(76, 76, 76);")
        self.FechaInicial.setCalendarPopup(True)
        self.FechaInicial.setObjectName("FechaInicial")
        self.FechaFinal = QtWidgets.QDateEdit(parent=Frame)
        self.FechaFinal.setGeometry(QtCore.QRect(300, 90, 151, 51))
        self.FechaFinal.setStyleSheet("background-color: rgb(18, 18, 18);\n"
"color: rgb(239, 205, 129);\n"
"selection-background-color: rgb(207, 175, 110);\n"
"selection-color: rgb(20, 20, 20);\n"
"alternate-background-color: rgb(76, 76, 76);\n"
"")
        self.FechaFinal.setCalendarPopup(True)
        self.FechaFinal.setObjectName("FechaFinal")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 181, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=Frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(280, 30, 181, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.BotonVolver = QtWidgets.QToolButton(parent=Frame)
        self.BotonVolver.setGeometry(QtCore.QRect(420, 440, 41, 31))
        self.BotonVolver.setStyleSheet("font-size: 30px;\n"
"")
        self.BotonVolver.setObjectName("BotonVolver")
        self.BotonImprimir = QtWidgets.QPushButton(parent=Frame)
        self.BotonImprimir.setGeometry(QtCore.QRect(20, 440, 101, 31))
        self.BotonImprimir.setStyleSheet("font: 35 10pt \"Cambria\";\n"
"\n"
"")
        self.BotonImprimir.setObjectName("BotonImprimir")
        self.ListaClientes = QtWidgets.QListWidget(parent=Frame)
        self.ListaClientes.setGeometry(QtCore.QRect(20, 200, 441, 231))
        self.ListaClientes.setStyleSheet("color: rgb(239, 205, 129);\n"
"font: 20px;")
        self.ListaClientes.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.ListaClientes.setObjectName("ListaClientes")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#edc97d;\">FECHA INICIAL</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#edc97d;\">FECHA FINAL</span></p></body></html>"))
        self.BotonVolver.setText(_translate("Frame", "⭠"))
        self.BotonImprimir.setText(_translate("Frame", "IMPRIMIR"))
