# Form implementation generated from reading ui file 'f:\Estudios\Visual Studio Code\2ºDAM\Interfaces\trabajo\Designs\MainDesign.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 610)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Inicio = QtWidgets.QFrame(parent=self.centralwidget)
        self.Inicio.setGeometry(QtCore.QRect(0, 0, 461, 611))
        self.Inicio.setStyleSheet("QFrame {\n"
"background-color: rgb(14, 13, 17);\n"
"border: 3px solid #edc97d;\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: rgb(237, 201, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(247, 222, 153);\n"
"}")
        self.Inicio.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Inicio.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Inicio.setObjectName("Inicio")
        self.label_icono = QtWidgets.QLabel(parent=self.Inicio)
        self.label_icono.setGeometry(QtCore.QRect(140, 30, 191, 191))
        self.label_icono.setStyleSheet("border: 0px solid;\n"
"background-color: rgb(14, 13, 17);")
        self.label_icono.setObjectName("label_icono")
        self.BotonIngresar = QtWidgets.QPushButton(parent=self.Inicio)
        self.BotonIngresar.setGeometry(QtCore.QRect(170, 400, 121, 41))
        self.BotonIngresar.setStyleSheet("font: 75 12pt \"Cambria\";\n"
"")
        self.BotonIngresar.setObjectName("BotonIngresar")
        self.MensajeError = QtWidgets.QLabel(parent=self.Inicio)
        self.MensajeError.setGeometry(QtCore.QRect(140, 460, 181, 20))
        self.MensajeError.setStyleSheet("border: 0px solid;\n"
"color: rgb(136, 0, 0);\n"
"text-align: center;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"")
        self.MensajeError.setObjectName("MensajeError")
        self.IDLabel = QtWidgets.QLineEdit(parent=self.Inicio)
        self.IDLabel.setGeometry(QtCore.QRect(150, 330, 161, 31))
        self.IDLabel.setStyleSheet("border: 2px solid #edc97d;\n"
"color: rgb(239, 205, 129);\n"
"font-size: 15px;\n"
"background-color: rgb(14, 13, 17);\n"
"")
        self.IDLabel.setObjectName("IDLabel")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.Inicio)
        self.textBrowser.setGeometry(QtCore.QRect(80, 260, 321, 51))
        self.textBrowser.setStyleSheet("border: 0px solid;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.Inicio)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 570, 351, 31))
        self.textBrowser_2.setStyleSheet("border: 0px solid;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_icono.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/logotipo.png\"/><img src=\":/Logo/logotipo.png\"/></p></body></html>"))
        self.BotonIngresar.setText(_translate("MainWindow", "INGRESAR"))
        self.MensajeError.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:18pt; font-weight:600; color:#edc97d;\">INGRESE SU CODIGO</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-style:italic; color:#f7de99;\">© 2025 Sofía Méndez. Todos los derechos reservados.</span></p></body></html>"))
