# Form implementation generated from reading ui file 'f:\Estudios\Visual Studio Code\2ºDAM\Interfaces\trabajo\Designs\SecondDesign.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(398, 465)
        Frame.setStyleSheet("QFrame {\n"
"background-color: rgb(18, 18, 18);\n"
"border: 3px solid rgb(239, 205, 129);\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: rgb(237, 201, 125);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(247, 222, 153);\n"
"}\n"
"\n"
"QToolButton {\n"
"background-color: rgb(237, 201, 125);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"background-color: rgb(247, 222, 153);\n"
"}")
        self.BotonFichar = QtWidgets.QPushButton(parent=Frame)
        self.BotonFichar.setGeometry(QtCore.QRect(100, 190, 191, 41))
        self.BotonFichar.setStyleSheet("font: 75 12pt \"Cambria\";\n"
"\n"
"")
        self.BotonFichar.setObjectName("BotonFichar")
        self.BotonImprimir = QtWidgets.QPushButton(parent=Frame)
        self.BotonImprimir.setGeometry(QtCore.QRect(100, 260, 191, 41))
        self.BotonImprimir.setStyleSheet("font: 75 12pt \"Cambria\";\n"
"\n"
"")
        self.BotonImprimir.setObjectName("BotonImprimir")
        self.BotonVolver = QtWidgets.QToolButton(parent=Frame)
        self.BotonVolver.setGeometry(QtCore.QRect(340, 420, 41, 31))
        self.BotonVolver.setStyleSheet("font-size: 30px;\n"
"")
        self.BotonVolver.setObjectName("BotonVolver")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Frame)
        self.textBrowser.setGeometry(QtCore.QRect(100, 20, 191, 51))
        self.textBrowser.setStyleSheet("border: 0px solid;")
        self.textBrowser.setObjectName("textBrowser")
        self.TextNombreUsuario = QtWidgets.QTextBrowser(parent=Frame)
        self.TextNombreUsuario.setGeometry(QtCore.QRect(60, 80, 271, 51))
        self.TextNombreUsuario.setStyleSheet("border: 0px solid;\n"
"text-align: center;\n"
"font-size: 20px;\n"
"color: rgb(239, 205, 129);")
        self.TextNombreUsuario.setObjectName("TextNombreUsuario")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.BotonFichar.setText(_translate("Frame", "FICHAR TRABAJO"))
        self.BotonImprimir.setText(_translate("Frame", "IMPRIMIR FICHAJES"))
        self.BotonVolver.setText(_translate("Frame", "⭠"))
        self.textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:18pt; font-weight:600; color:#edc97d;\">BIENVENID@</span></p></body></html>"))
        self.TextNombreUsuario.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
